pipeline {
    agent {label 'windowslave'}
    stages {
        stage('Clonning the repo') {
            steps {
                echo "To call username use "
                echo "To call password use "
            }
        }
    }
}
